name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Oracle Cloud via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/cido-project/cido-frontend
            git pull origin main
            npm install
            npm run build
            
            # Nginx 설정 생성 (80 포트를 3000 포트로 프록시)
            sudo tee /etc/nginx/sites-available/cidofactory.com > /dev/null <<'EOF'
            server {
                listen 80;
                server_name cidofactory.com www.cidofactory.com;

                location / {
                    proxy_pass http://localhost:3000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
            EOF
            
            # Nginx 설정 활성화
            sudo ln -sf /etc/nginx/sites-available/cidofactory.com /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo nginx -t && sudo systemctl reload nginx
            
            # PM2로 실행 중이면
            if pm2 list | grep -q cido-frontend; then
              pm2 restart cido-frontend
            # 그냥 node 프로세스면
            else
              pkill -f "next\|node.*3000" || true
              pm2 start npm --name "cido-frontend" -- start
              pm2 save
            fi
            
            echo "Deployment completed successfully!"
            pm2 status cido-frontend

