name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Oracle Cloud via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/cido-project/cido-frontend
            git pull origin main
            npm install
            npm run build
            
            # PM2로 실행 중이면
            if pm2 list | grep -q cido-frontend; then
              pm2 restart cido-frontend
            # 그냥 node 프로세스면
            else
              pkill -f "next\|node.*8080" || true
              nohup npm run start > /dev/null 2>&1 &
            fi
            
            echo "Deployment completed successfully!"

